# Generated by Django 5.1.1 on 2024-10-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questiontag',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questiontag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
