# Generated by Django 5.1.1 on 2024-10-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_rename_user_id_question_user_and_more'),
        ('adminapp', '0005_tag_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(through='QA.QuestionTag', to='adminapp.tag'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='QA.question'),
        ),
    ]
