# Generated by Django 5.1.1 on 2024-11-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0007_savedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
