# Generated by Django 5.1.1 on 2024-11-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('question', 'Question'), ('message', 'Message'), ('order_status', 'Order Status')], max_length=20),
        ),
    ]
