# Generated by Django 5.1.1 on 2024-10-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='a language', max_length=100),
            preserve_default=False,
        ),
    ]
