# Generated by Django 5.1.1 on 2024-10-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
