# Generated by Django 5.1.1 on 2024-10-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_blocked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
