# Generated by Django 5.1.1 on 2024-10-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_users_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auth_provider',
            field=models.CharField(default='email', max_length=50),
        ),
    ]
